export const phdCredits = "3 (3+0)";

export const phdCourses = [
	["1", "EE-801", "Advanced Control System"],
	["2", "EE-802", "Advanced Power Electronics"],
	["3", "EE-803", "Applied Machine Learning"],
	["4", "EE-804", "Research Methodology"],
	["5", "EE-805", "Advanced Electrical Machines"],
	["6", "EE-806", "Advanced Power Systems"],
	["7", "EE-807", "Sustainable Energy Systems"],
	["8", "EE-808", "Advanced Digital Signal Processing"],
	["9", "EE-809", "Advanced VLSI Systems Design"],
	["10", "EE-810", "Advanced Radio Frequency Circuit Design"],
	["11", "EE-811", "Advanced Networked Systems"],
	["12", "EE-812", "Electricity Markets"],
	["13", "EE-813", "Smart Grid Systems"],
	["14", "EE-814", "Internet of Things Based Systems"],
	["15", "EE-815", "Satellite Communication and Navigational Aids (replaced with EE-841)"],
	["16", "EE-816", "Modeling and Simulation"],
	["17", "EE-817", "High Voltage DC Transmission"],
	["18", "EE-818", "Advanced Digital Communication"],
	["19", "EE-819", "Electronic Materials and Devices"],
	["20", "EE-820", "IC Design and Packaging Technologies"],
	["21", "EE-821", "RF MEMS Theory and Application"],
	["22", "EE-822", "Photovoltaic Power System Design"],
	["23", "EE-823", "Advanced Mobile and Wireless Communication"],
	["24", "EE-824", "Swarm Robotics and Bio Inspired Robotics"],
	["25", "EE-825", "Advanced Digital Image Processing"],
	["26", "EE-826", "Power System Analysis and Design"],
	["28", "EE-828", "Distributed Generation and Smart Grids"],
	["28", "EE-828", "Robust Control in Power Systems"],
	["29", "EE-829", "Advanced Power System Protection"],
	["30", "EE-830", "Power Systems Stability and Control"],
	["31", "EE-831", "Power Converter Design"],
	["32", "EE-832", "Digital Control System and Design"],
	["33", "EE-833", "Transmission and Distribution System Engineering"],
	["34", "EE-834", "Advanced Computer Networks and Security"],
	["35", "EE-835", "Advanced Power Conversion"],
	["36", "EE-836", "Advanced Digital Systems Design"],
	["37", "EE-837", "Advanced Topics in RF and Microwave"],
	["38", "EE-838", "Distributed Generation and Microgrids"],
	["39", "EE-839", "Advanced Communication Networks"],
	["40", "EE-840", "Advanced Integrated Circuits"],
	["41", "EE-841", "Advanced Satellite Communication"],
	["42", "EE-842", "Advanced Nano Technologies"],
	["43", "EE-843", "Computer Vision"],
	["44", "EE-844", "Autonomous Vehicle Systems"],
	["45", "EE-845", "Advanced Optical Communication Systems"],
	["46", "EE-846", "Information and Coding Theory"],
	["47", "EE-848", "Wireless Sensor Networks"],
	["48", "EE-848", "Signal Detection and Estimation"],
	["49", "EE-849", "Radio Frequency Identification (RFID) Systems"],
	["50", "EE-850", "Analysis of Algorithms"],
	["51", "EE-851", "Optimization Techniques"],
	["52", "EE-852", "Advanced Probability and Stochastic Processes"],
	["53", "EE-853", "Professional Leadership Development"],
];
