const credits = "3 (3+0)";

export const phdCourses = [
  ["1", "EE-801", "Advanced Control System", credits],
  ["2", "EE-802", "Advanced Power Electronics", credits],
  ["3", "EE-803", "Applied Machine Learning", credits],
  ["4", "EE-804", "Research Methodology", credits],
  ["5", "EE-805", "Advanced Electrical Machines", credits],
  ["6", "EE-806", "Advanced Power Systems", credits],
  ["7", "EE-807", "Sustainable Energy Systems", credits],
  ["8", "EE-808", "Advanced Digital Signal Processing", credits],
  ["9", "EE-809", "Advanced VLSI Systems Design", credits],
  ["10", "EE-810", "Advanced Radio Frequency Circuit Design", credits],
  ["11", "EE-811", "Advanced Networked Systems", credits],
  ["12", "EE-812", "Electricity Markets", credits],
  ["13", "EE-813", "Smart Grid Systems", credits],
  ["14", "EE-814", "Internet of Things Based Systems", credits],
  ["15", "EE-815", "Satellite Communication and Navigational Aids (replaced with EE-841)", credits],
  ["16", "EE-816", "Modeling and Simulation", credits],
  ["17", "EE-817", "High Voltage DC Transmission", credits],
  ["18", "EE-818", "Advanced Digital Communication", credits],
  ["19", "EE-819", "Electronic Materials and Devices", credits],
  ["20", "EE-820", "IC Design and Packaging Technologies", credits],
  ["21", "EE-821", "RF MEMS Theory and Application", credits],
  ["22", "EE-822", "Photovoltaic Power System Design", credits],
  ["23", "EE-823", "Advanced Mobile and Wireless Communication", credits],
  ["24", "EE-824", "Swarm Robotics and Bio Inspired Robotics", credits],
  ["25", "EE-825", "Advanced Digital Image Processing", credits],
  ["26", "EE-826", "Power System Analysis and Design", credits],
  ["28", "EE-828", "Distributed Generation and Smart Grids", credits],
  ["28", "EE-828", "Robust Control in Power Systems", credits],
  ["29", "EE-829", "Advanced Power System Protection", credits],
  ["30", "EE-830", "Power Systems Stability and Control", credits],
  ["31", "EE-831", "Power Converter Design", credits],
  ["32", "EE-832", "Digital Control System and Design", credits],
  ["33", "EE-833", "Transmission and Distribution System Engineering", credits],
  ["34", "EE-834", "Advanced Computer Networks and Security", credits],
  ["35", "EE-835", "Advanced Power Conversion", credits],
  ["36", "EE-836", "Advanced Digital Systems Design", credits],
  ["37", "EE-837", "Advanced Topics in RF and Microwave", credits],
  ["38", "EE-838", "Distributed Generation and Microgrids", credits],
  ["39", "EE-839", "Advanced Communication Networks", credits],
  ["40", "EE-840", "Advanced Integrated Circuits", credits],
  ["41", "EE-841", "Advanced Satellite Communication", credits],
  ["42", "EE-842", "Advanced Nano Technologies", credits],
  ["43", "EE-843", "Computer Vision", credits],
  ["44", "EE-844", "Autonomous Vehicle Systems", credits],
  ["45", "EE-845", "Advanced Optical Communication Systems", credits],
  ["46", "EE-846", "Information and Coding Theory", credits],
  ["47", "EE-848", "Wireless Sensor Networks", credits],
  ["48", "EE-848", "Signal Detection and Estimation", credits],
  ["49", "EE-849", "Radio Frequency Identification (RFID) Systems", credits],
  ["50", "EE-850", "Analysis of Algorithms", credits],
  ["51", "EE-851", "Optimization Techniques", credits],
  ["52", "EE-852", "Advanced Probability and Stochastic Processes", credits],
  ["53", "EE-853", "Professional Leadership Development", credits],
];